global:
  seed: 2023
  loss_alpha: 0.1
  optimizer: 'Adam'
  ground: False

# specific configurations of each model
GCN:
  num_layers: 4
  hidden: 256
  learning_rate: 0.01
  dropout: 0.8
  weight_decay: 0.001
  temp: 1.0
  att: False
  layer_flag: False
GAT:
  num_layers: 3
  hidden: 256
  learning_rate: 0.01
  dropout: 0.6
  att_dropout: 0.3
  alpha: 0.2
  weight_decay: 0.01
  temp: 1.0
  num_heads: 8
  att: True
  layer_flag: False
GraphSAGE:
  agg_type: 'gcn'   # mean/gcn/pool/lstm
  num_layers: 4
  dropout: 0.6
  embed_dim: 256
  batch_size: 256
  num_samples: 10
  learning_rate: 0.01
  weight_decay: 0.0005
#  optimizer: 'SGD'
  att: False
  layer_flag: False
GCNII:
  learning_rate: 0.01
  wd1: 0.01
  wd2: 0.0005
  layer: 16
  hidden: 256
  dropout: 0.6
  alpha: 0.1
  lamda: 0.5